version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    ports: 
      - "5433:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - "4000:4000"
    depends_on:
      - db
  web:
    build: ./web
    volumes:
      - ./web:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
